development:
  adapter: postgresql
  database: my_story_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_story_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_story_production
  pool: 5
  timeout: 5000
